Repository MiguelPerezMartinez/php-employee-management-v2, pull requests merged in 2021-07, with the labels that each got.

#5 feat: Router.php and .htaccess created and working
  .htaccess
  index.php
  src/libs/router.php
Labels: enhancement

#6 feat: SQL db created
  V1/resources/images_mock.json
  V1/resources/users.json
  db/create_db.sql
Labels: enhancement

#8 Feat/model creation
  assets/css/login.css
  assets/css/main.css
  assets/html/footer.html
  assets/html/header.html
  assets/images/Alfonso y Erick Logotipos.gif
  assets/images/Blue Cool and Funky Gaming Logo.gif
  assets/js/general.js
  assets/js/index.js
  assets/templates/Footer.php
  assets/templates/footer.html
  assets/templates/header.php
  config/constants.php
  config/db.php
  config/executionFlow.php
  db/create_db.sql
  index.php
  src/controllers/EmployeeController.php
  src/controllers/LoginController.php
  src/libs/classes/Controller.php
  src/libs/classes/Model.php
  src/libs/classes/View.php
  src/libs/database.php
  src/libs/router.php
  src/models/EmployeeModel.php
  src/models/LoginModel.php
  src/views/Employee/dashboard.php
  src/views/Login/index.php
  temp/employees.json
Labels: enhancement

#9 Feat/login flow
  assets/templates/header.html
  src/controllers/EmployeeController.php
  src/controllers/LoginController.php
  src/libs/classes/Controller.php
  src/libs/classes/Model.php
  src/libs/classes/View.php
  src/libs/database.php
  src/libs/router.php
  src/models/EmployeeModel.php
  src/models/LoginModel.php
  src/views/Employee/dashboard.php
  src/views/Login/index.php
Labels: enhancement

#13 feat: session controller
  V1/src/library/avatarsApi.php
  assets/templates/header.php
  index.php
  src/controllers/EmployeeController.php
  src/controllers/LoginController.php
  src/controllers/SessionController.php
  src/libs/router.php
  src/models/LoginModel.php
Labels: enhancement

#23 modify session controller and correcting bugs
  src/controllers/EmployeeController.php
  src/controllers/LoginController.php
  src/libs/classes/Controller.php
  src/views/Login/index.php
Labels: bug

#25 Feat/dashboard functions
  assets/js/index.js
  assets/templates/header.html
  assets/templates/header.php
  src/controllers/EmployeeController.php
  src/models/EmployeeModel.php
  src/views/Employee/dashboard.php
  src/views/Employee/employee.php
  temp/employees.json
Labels: enhancement

#24 Fix/some fixes
  config/db.php
  index.php
  src/controllers/EmployeeController.php
  src/controllers/SessionController.php
  src/libs/database.php
Labels: bug, enhancement, fix

#26 Fix: sql error solved
  assets/css/main.css
  assets/js/index.js
  assets/templates/header.php
  db/create_db.sql
  src/controllers/EmployeeController.php
Labels: fix

#28 Feat: error handling
  assets/images/error_image.png
  db/create_db.sql
  src/controllers/EmployeeController.php
  src/controllers/ErrorController.php
  src/models/EmployeeModel.php
  src/views/Employee/dashboard.php
  src/views/Employee/employee.php
  src/views/Error/error.php
  src/views/Login/index.php
Labels: enhancement

#29 Feat/dynamic navbar
  assets/css/login.css
  assets/js/index.js
  assets/templates/footer.html
  assets/templates/header.php
  src/controllers/EmployeeController.php
  src/controllers/UserController.php
  src/libs/classes/Controller.php
  src/libs/classes/Model.php
  src/libs/classes/View.php
  src/models/EmployeeModel.php
  src/models/LoginModel.php
  src/models/UserModel.php
  src/views/Login/index.php
  src/views/User/dashboard.php
Labels: bug, enhancement

#30 Feat: error handling - login
  assets/images/error_server.png
  src/controllers/LoginController.php
  src/libs/database.php
  src/models/LoginModel.php
  src/views/Error/connection.php
Labels: enhancement

#31 feat: readme created
  README.md
Labels: enhancement

#32 Update README.md
  README.md
Labels: enhancement
